Repository AxaFrance/design-system, pull requests merged in 2024-02, with the labels that each got.

#108 fix(RadioItem): disabled radio options should not be selectable
  packages/react/src/Form/Radio/RadioItem.tsx
Labels: bug

#104 feat(Choice): add agent Choice component
  packages/css/src/Form/Choice/Choice.agent.scss
  packages/css/src/Form/Choice/Choice.agent.stories.ts
  packages/css/src/agent.scss
  packages/react/src/Form/Choice/Choice.mdx
  packages/react/src/Form/Choice/Choice.stories.tsx
  packages/react/src/Form/Choice/Choice.tsx
  packages/react/src/Form/Choice/ChoiceInput.stories.tsx
  packages/react/src/Form/Choice/ChoiceInput.tsx
  packages/react/src/Form/Choice/index.ts
  packages/react/src/agent.ts
Labels: agent-slash, component

#116 fix(button client): style ghost + var rename
  packages/css/src/Button/Button.client.scss
  packages/css/src/common/common.client.scss
  packages/react/src/Button/Button.client.stories.tsx
Labels: look'n feel

#114 Feature/icons client
  packages/react/.storybook/main.js
  packages/react/src/Icons/Icon.client.stories.css
  packages/react/src/Icons/Icon.client.stories.tsx
Labels: look'n feel

#110 feature/footer-component
  config/eslint.config.js
  config/postcss.config.js
  packages/css/.prettierignore
  packages/css/src/Layout/Footer/Footer.scss
  packages/css/src/Layout/Footer/Footer.stories.ts
  packages/css/src/agent.scss
  packages/css/src/common/assets/logo-axa.svg
  packages/css/src/env.d.ts
  packages/css/tsconfig.json
  packages/react/src/Layout/Footer/Footer.mdx
  packages/react/src/Layout/Footer/Footer.stories.tsx
  packages/react/src/Layout/Footer/Footer.tsx
  packages/react/src/Layout/Footer/index.ts
  packages/react/src/agent.ts
  packages/react/src/env.d.ts
  packages/react/tsconfig.json
Labels: agent-slash

#128 feat: add footer client
  packages/css/src/Footer/Footer.client.scss
  packages/css/src/Footer/Footer.client.stories.ts
  packages/css/src/common/common.client.scss
  packages/react/src/Footer/DynamicIcons.client.tsx
  packages/react/src/Footer/Footer.client.mdx
  packages/react/src/Footer/Footer.client.stories.tsx
  packages/react/src/Footer/Footer.client.tsx
  packages/react/src/Footer/MenuIcons.client.tsx
  packages/react/src/Footer/MenuLink.client.tsx
Labels: look'n feel

#118 feat: add header (simple)
  packages/css/src/Header/Header.client.scss
  packages/css/src/Header/Header.client.stories.ts
  packages/css/src/common/common.client.scss
  packages/react/src/Header/Header.client.mdx
  packages/react/src/Header/Header.client.stories.css
  packages/react/src/Header/Header.client.stories.tsx
  packages/react/src/Header/Header.client.tsx
  packages/react/src/client.ts
Labels: look'n feel

#138 fix: export footer client
  packages/react/src/client.ts
Labels: look'n feel

#141 fix: css dependency
  package-lock.json
  packages/react/package.json
Labels: dependencies

#140 docs: add a vite sample to showcase components
  .github/workflows/publish.yml
  package-lock.json
  package.json
  packages/react/.storybook/main.js
  samples/vite/.eslintrc.cjs
  samples/vite/.gitignore
  samples/vite/index.html
  samples/vite/package.json
  samples/vite/public/vite.svg
  samples/vite/src/App.css
  samples/vite/src/App.tsx
  samples/vite/src/Reset.css
  samples/vite/src/main.tsx
  samples/vite/src/vite-env.d.ts
  samples/vite/tsconfig.json
  samples/vite/tsconfig.node.json
  samples/vite/vite.config.ts
Labels: tooling

#146 feature/component-badge
  packages/css/src/Badge/Badge.scss
  packages/css/src/Badge/Badge.stories.ts
  packages/css/src/agent.scss
  packages/react/src/Badge/Badge.mdx
  packages/react/src/Badge/Badge.stories.tsx
  packages/react/src/Badge/Badge.tsx
Labels: agent-slash

#161 fix: export Button Variants and css client missing
  packages/css/src/client.scss
  packages/react/src/client.ts
  samples/vite/src/App.tsx
Labels: look'n feel
