Repository AxaFrance/design-system, pull requests merged in 2024-05, with the labels that each got.

#292 fix(checkbox): add forwardRef on checkbox component
  packages/react/src/Form/Checkbox/Client/Checkbox.mdx
  packages/react/src/Form/Checkbox/Client/Checkbox.tsx
  packages/react/src/Form/Checkbox/Client/CheckboxSelect.stories.tsx
  packages/react/src/Form/Checkbox/Client/index.ts
  packages/react/src/client.ts
Labels: look'n feel

#298 fix: client Radio and RadioSelect
  packages/css/src/Form/Checkbox/Client/Checkbox.scss
  packages/css/src/Form/Radio/Client/Radio.scss
  packages/css/src/Form/Radio/Client/Radio.stories.ts
  packages/react/src/Form/Radio/Client/Radio.mdx
  packages/react/src/Form/Radio/Client/Radio.stories.tsx
  packages/react/src/Form/Radio/Client/Radio.tsx
  packages/react/src/Form/Radio/Client/RadioInput.stories.tsx
  packages/react/src/Form/Radio/Client/RadioInput.tsx
  packages/react/src/Form/Radio/Client/RadioItem.stories.tsx
  packages/react/src/Form/Radio/Client/RadioItem.tsx
  packages/react/src/Form/Radio/Client/RadioSelect.stories.tsx
  packages/react/src/Form/Radio/Client/RadioSelect.tsx
  packages/react/src/Form/Radio/Client/index.ts
  packages/react/src/client.ts
Labels: look'n feel

#291 feature: input text client
  packages/css/src/Form/Text/Agent/Text.agent.scss
  packages/css/src/Form/Text/Agent/Text.stories.ts
  packages/css/src/Form/Text/Agent/TextInput.stories.ts
  packages/css/src/Form/Text/Client/Text.client.scss
  packages/css/src/Form/Text/Client/Text.stories.ts
  packages/css/src/agent.scss
  packages/react/src/Form/Number/Number.tsx
  packages/react/src/Form/Text/Agent/Text.mdx
  packages/react/src/Form/Text/Agent/Text.stories.tsx
  packages/react/src/Form/Text/Agent/Text.tsx
  packages/react/src/Form/Text/Agent/TextInput.stories.tsx
  packages/react/src/Form/Text/Agent/TextInput.tsx
  packages/react/src/Form/Text/Agent/index.ts
  packages/react/src/Form/Text/Agent/inputTypes.ts
  packages/react/src/Form/Text/Client/Text.stories.tsx
  packages/react/src/Form/Text/Client/Text.tsx
  packages/react/src/Form/Text/Client/index.ts
  packages/react/src/agent.ts
  packages/react/src/client.ts
Labels: look'n feel

#304 feat(Agent TextInput): add forwardRef
  packages/react/src/Form/Text/Agent/TextInput.tsx
Labels: agent-slash, component

#306 feat(Agent Form): add customProps Option property
  packages/react/src/Form/Checkbox/Agent/Checkbox.tsx
  packages/react/src/Form/Checkbox/Agent/CheckboxInput.tsx
  packages/react/src/Form/Radio/Agent/Radio.tsx
  packages/react/src/Form/Radio/Agent/RadioInput.tsx
  packages/react/src/Form/core/index.ts
  packages/react/src/Form/core/useOptionsWithId.ts
Labels: agent-slash, component

#308 feat(Agent Select): add forwardRef
  packages/react/src/Form/Select/Select.tsx
  packages/react/src/Form/Select/SelectDefault.tsx
  packages/react/src/Form/Select/SelectInput.tsx
Labels: agent-slash, component

#310 feat(Agent Textarea): add forwardRef
  packages/react/src/Form/Textarea/TextareaInput.tsx
Labels: agent-slash, component

#311 feat(agent): make onChange Checkbox prop optional
  packages/react/src/Form/Checkbox/Agent/Checkbox.tsx
Labels: agent-slash, component

#326 fix(RadioSelect client): correct options id generated
  packages/react/src/Form/Radio/Client/RadioSelect.stories.tsx
  packages/react/src/Form/Radio/Client/RadioSelect.tsx
Labels: look'n feel

#179 feat(Header): implement header agent component
  package.json
  packages/css/package.json
  packages/css/src/Layout/Header/Drawer/Drawer.scss
  packages/css/src/Layout/Header/Header.agent.scss
  packages/css/src/Layout/Header/Header.agent.stories.ts
  packages/css/src/Layout/Header/Header.client.scss
  packages/css/src/Layout/Header/Header.client.stories.ts
  packages/css/src/Layout/Header/Infos/Infos.scss
  packages/css/src/Layout/Header/Infos/Infos.stories.ts
  packages/css/src/Layout/Header/Logo/Logo.scss
  packages/css/src/Layout/Header/Name/Name.scss
  packages/css/src/Layout/Header/Name/Name.stories.ts
  packages/css/src/Layout/Header/NavBar/NavBar.stories.ts
  packages/css/src/Layout/Header/TitleHeader/TitleHeader.scss
  packages/css/src/Layout/Header/TitleHeader/TitleHeader.stories.ts
  packages/css/src/Layout/Header/User/User.scss
  packages/css/src/Layout/Header/User/User.stories.ts
  packages/css/src/agent.scss
  packages/css/src/client.scss
  packages/css/src/common/common.agent.scss
  packages/react/package.json
  packages/react/src/Layout/Header/Header.agent.mdx
  packages/react/src/Layout/Header/Header.agent.stories.tsx
  packages/react/src/Layout/Header/Header.agent.tsx
  packages/react/src/Layout/Header/Header.client.mdx
  packages/react/src/Layout/Header/Header.client.stories.css
  packages/react/src/Layout/Header/Header.client.stories.tsx
  packages/react/src/Layout/Header/Header.client.tsx
  packages/react/src/Layout/Header/Infos/Infos.mdx
  packages/react/src/Layout/Header/Infos/Infos.stories.tsx
  packages/react/src/Layout/Header/Infos/Infos.tsx
  packages/react/src/Layout/Header/MenuTitleWrapper/MenuTitleWrapper.mdx
  packages/react/src/Layout/Header/MenuTitleWrapper/MenuTitleWrapper.stories.tsx
  packages/react/src/Layout/Header/MenuTitleWrapper/MenuTitleWrapper.tsx
  packages/react/src/Layout/Header/Name/Name.mdx
  packages/react/src/Layout/Header/Name/Name.stories.tsx
  packages/react/src/Layout/Header/Name/Name.tsx
  packages/react/src/Layout/Header/TitleHeader/TitleHeader.helpers.ts
  packages/react/src/Layout/Header/TitleHeader/TitleHeader.mdx
  packages/react/src/Layout/Header/TitleHeader/TitleHeader.stories.tsx
  packages/react/src/Layout/Header/TitleHeader/TitleHeader.tsx
  packages/react/src/Layout/Header/ToggleButton/ToggleButton.mdx
  packages/react/src/Layout/Header/ToggleButton/ToggleButton.stories.tsx
  packages/react/src/Layout/Header/ToggleButton/ToggleButton.ts
  packages/react/src/Layout/Header/User/InnerUser.tsx
  packages/react/src/Layout/Header/User/User.mdx
  packages/react/src/Layout/Header/User/User.stories.tsx
  packages/react/src/Layout/Header/User/User.tsx
  packages/react/src/Layout/Header/index.ts
  packages/react/src/agent.ts
  packages/react/src/client.ts
Labels: agent-slash

#329 fix(Select): remove select option when defaultValue is defined
  packages/react/src/Form/Select/SelectDefault.tsx
Labels: agent-slash, component

#331 fix(checkbox client): add classname prop and right check icon
  packages/react/src/Form/Checkbox/Client/Checkbox.tsx
  packages/react/src/Form/Checkbox/Client/CheckboxSelect.tsx
Labels: look'n feel

#296 feature: component select client
  package-lock.json
  packages/css/src/Form/Select/Agent/Select.agent.scss
  packages/css/src/Form/Select/Agent/Select.agent.stories.ts
  packages/css/src/Form/Select/Client/Select.client.scss
  packages/css/src/Form/Select/Client/Select.client.stories.ts
  packages/css/src/agent.scss
  packages/css/src/client.scss
  packages/css/src/common/common.client.scss
  packages/react/package.json
  packages/react/src/Form/Select/Agent/Select.mdx
  packages/react/src/Form/Select/Agent/Select.stories.tsx
  packages/react/src/Form/Select/Agent/Select.tsx
  packages/react/src/Form/Select/Agent/SelectBase.tsx
  packages/react/src/Form/Select/Agent/SelectDefault.tsx
  packages/react/src/Form/Select/Agent/SelectInput.stories.tsx
  packages/react/src/Form/Select/Agent/SelectInput.tsx
  packages/react/src/Form/Select/Agent/index.ts
  packages/react/src/Form/Select/Client/DropdownIndicator.tsx
  packages/react/src/Form/Select/Client/Select.stories.tsx
  packages/react/src/Form/Select/Client/Select.tsx
  packages/react/src/Form/Select/Client/index.ts
  packages/react/src/agent.ts
  packages/react/src/client.ts
Labels: component, look'n feel

#335 feat(Agent Choice): update ChoiceInput and Choice components to use forwardRef
  packages/react/src/Form/Choice/Choice.tsx
  packages/react/src/Form/Choice/ChoiceInput.tsx
Labels: agent-slash, component
