Repository AxaFrance/design-system, pull requests merged in 2024-06, with the labels that each got.

#314 feature: component file upload client
  packages/css/src/Form/FileUpload/Client/FileUpload.client.scss
  packages/css/src/Form/FileUpload/Client/FileUpload.stories.ts
  packages/css/src/client.scss
  packages/react/src/Form/FileUpload/Client/FIleUpload.stories.tsx
  packages/react/src/Form/FileUpload/Client/FileUpload.tsx
  packages/react/src/Form/FileUpload/Client/index.ts
  packages/react/src/client.ts
Labels: component, look'n feel

#327 feature: create MultiSelect component
  package-lock.json
  packages/css/src/Form/MultiSelect/MultiSelect.agent.scss
  packages/css/src/agent.scss
  packages/react/src/Form/MultiSelect/MultiSelect.mdx
  packages/react/src/Form/MultiSelect/MultiSelect.stories.tsx
  packages/react/src/Form/MultiSelect/MultiSelect.tsx
  packages/react/src/Form/MultiSelect/MultiSelectInput.tsx
  packages/react/src/Form/MultiSelect/__tests__/MultiSelect.spec.tsx
  packages/react/src/Form/MultiSelect/__tests__/MultiSelectInput.spec.tsx
  packages/react/src/Form/MultiSelect/__tests__/__snapshots__/MultiSelect.spec.tsx.snap
  packages/react/src/Form/MultiSelect/__tests__/__snapshots__/MultiSelectInput.spec.tsx.snap
  packages/react/src/Form/MultiSelect/index.ts
  packages/react/src/agent.ts
Labels: agent-slash, component, css-package

#353 chore: define css version in react on publish
  .github/workflows/publish.yml
  package-lock.json
  packages/react/package.json
Labels: chore, design

#359 fix(agent): set input id instead of container id for MultiSelect and MultiSelectInput
  packages/react/src/Form/MultiSelect/MultiSelect.tsx
  packages/react/src/Form/MultiSelect/MultiSelectInput.tsx
  packages/react/src/Form/MultiSelect/__tests__/__snapshots__/MultiSelect.spec.tsx.snap
  packages/react/src/Form/MultiSelect/__tests__/__snapshots__/MultiSelectInput.spec.tsx.snap
Labels: agent-slash, component
