Repository AxaFrance/design-system, pull requests merged in 2024-04, with the labels that each got.

#248 fix: modal client max min width
  packages/css/src/Modal/Modal.client.scss
Labels: look'n feel

#218 refactor(Footer): move agent and client to the same root folder
  packages/css/src/Layout/Footer/Footer.agent.scss
  packages/css/src/Layout/Footer/Footer.agent.stories.ts
  packages/css/src/Layout/Footer/Footer.client.scss
  packages/css/src/Layout/Footer/Footer.client.stories.ts
  packages/css/src/agent.scss
  packages/css/src/client.scss
  packages/react/src/Layout/Footer/Agent/Footer.mdx
  packages/react/src/Layout/Footer/Agent/Footer.stories.tsx
  packages/react/src/Layout/Footer/Agent/Footer.tsx
  packages/react/src/Layout/Footer/Agent/index.ts
  packages/react/src/Layout/Footer/Client/DynamicIcons.tsx
  packages/react/src/Layout/Footer/Client/Footer.mdx
  packages/react/src/Layout/Footer/Client/Footer.stories.tsx
  packages/react/src/Layout/Footer/Client/Footer.tsx
  packages/react/src/Layout/Footer/Client/MenuIcons.tsx
  packages/react/src/Layout/Footer/Client/MenuLink.tsx
  packages/react/src/agent.ts
  packages/react/src/client.ts
Labels: good first issue

#226 Feature/add tests
  config/eslint.config.js
  package-lock.json
  packages/react/.eslintrc.js
  packages/react/package.json
  packages/react/src/Title/__tests__/Title.test.tsx
  packages/react/tsconfig.json
  packages/react/vitest.config.ts
  packages/react/vitest.setup.ts
Labels: chore, tooling

#267 fix(packages): regenerate package-lock.json to make tests runnable
  package-lock.json
Labels: bug, chore, dependencies

#280 feat: remplacement de @mui/icons-material par @material-design-icons/svg
  README.md
  package-lock.json
  packages/css/package.json
  packages/react/package.json
  packages/react/src/Alert/Alert.client.tsx
  packages/react/src/Button/Button.client.stories.tsx
  packages/react/src/Form/Checkbox/Client/Checkbox.stories.tsx
  packages/react/src/Form/Checkbox/Client/Checkbox.tsx
  packages/react/src/Form/Checkbox/Client/CheckboxSelect.stories.tsx
  packages/react/src/Form/Checkbox/Client/CheckboxSelect.tsx
  packages/react/src/Form/Radio/Client/Radio.stories.tsx
  packages/react/src/Form/Radio/Client/RadioInput.stories.tsx
  packages/react/src/Form/Radio/Client/RadioInput.tsx
  packages/react/src/Form/Radio/Client/RadioItem.stories.tsx
  packages/react/src/Header/Header.client.stories.tsx
  packages/react/src/Icons/Icon.client.stories.tsx
  packages/react/src/Icons/Icon.client.tsx
  packages/react/src/Layout/Footer/Client/DynamicIcons.tsx
  packages/react/src/Layout/Footer/Client/Footer.tsx
  packages/react/src/Link/Link.client.tsx
  packages/react/src/ModalClient/Modal.client.stories.tsx
  packages/react/src/ModalClient/Modal.client.tsx
  packages/react/src/Pagination/PaginationMobile.client.tsx
  packages/react/src/Svg/Svg.agent.mdx
  packages/react/src/Svg/Svg.agent.stories.tsx
  packages/react/src/Svg/Svg.client.mdx
  packages/react/src/Svg/Svg.client.stories.tsx
  packages/react/src/Svg/Svg.stories.css
  packages/react/src/Svg/Svg.tsx
  packages/react/src/Svg/__tests__/Svg.test.tsx
  packages/react/src/Svg/index.ts
  packages/react/src/Svg/svgInjector.ts
  packages/react/src/agent.ts
  packages/react/src/assets/svg/facebook.svg
  packages/react/src/assets/svg/linkedin.svg
  packages/react/src/assets/svg/twitterx.svg
  packages/react/src/assets/svg/youtube.svg
  packages/react/src/client.ts
  samples/vite/package.json
  samples/vite/src/App.tsx
Labels: agent-slash, component, look'n feel

#282 feat: can add icons to tabs button
  packages/css/src/Tabs/Tabs.client.stories.ts
  packages/react/src/Tabs/Client/Tabs.client.mdx
  packages/react/src/Tabs/Client/Tabs.client.stories.tsx
  packages/react/src/Tabs/Client/Tabs.client.tsx
Labels: look'n feel

#217 feature(agent): Navigation
  packages/css/src/Layout/Header/NavBar/NavBar.scss
  packages/css/src/Layout/Header/NavBar/NavBar.stories.ts
  packages/css/src/agent.scss
  packages/css/src/common/common.agent.scss
  packages/react/src/Layout/Header/NavBar/NavBar.helpers.ts
  packages/react/src/Layout/Header/NavBar/NavBar.stories.tsx
  packages/react/src/Layout/Header/NavBar/NavBar.tsx
  packages/react/src/Layout/Header/NavBar/NavBarBase.tsx
  packages/react/src/Layout/Header/NavBar/NavBarItem/NavBarItem.stories.tsx
  packages/react/src/Layout/Header/NavBar/NavBarItem/NavBarItem.tsx
  packages/react/src/Layout/Header/NavBar/NavBarItem/NavBarItemBase.helpers.tsx
  packages/react/src/Layout/Header/NavBar/NavBarItem/NavBarItemBase.tsx
  packages/react/src/Layout/Header/NavBar/NavBarItem/NavBarItemLink.tsx
  packages/react/src/Layout/Header/NavBar/NavBarItem/index.ts
  packages/react/src/Layout/Header/NavBar/index.ts
  packages/react/src/Layout/Header/index.ts
  packages/react/src/agent.ts
Labels: agent-slash, component

#289 fix: icon checkbox client
  packages/react/src/Form/Checkbox/Client/Checkbox.tsx
Labels: look'n feel

#269 chore(ci): add test execution
  .github/workflows/main.yml
  packages/react/vitest.config.mts
Labels: enhancement, chore
